ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4)

      DOUBLE PRECISION ME,MB,MM,MH,MT,MW,MTA,MZ

      COMMON/MASSES/ ME,MB,MM,MH,MT,MW,MTA,MZ


      DOUBLE PRECISION WW,WT,WZ,WH

      COMMON/WIDTHS/ WW,WT,WZ,WH


      DOUBLE COMPLEX GC_6, GC_7, GC_13, GC_22, GC_23, GC_31, GC_32
     $ , GC_38, GC_39, GC_40, GC_41, GC_42, GC_43, GC_44, GC_45

      COMMON/COUPLINGS/ GC_6, GC_7, GC_13, GC_22, GC_23, GC_31, GC_32
     $ , GC_38, GC_39, GC_40, GC_41, GC_42, GC_43, GC_44, GC_45

