      *     1       1
      -1 8  7   MDL_MW  MDL_WW    S -24
      -2 -1  6   MDL_MT  MDL_WT    S -6
      -3 5  4   MDL_MW  MDL_WW    S 24
      -4 -3  3   MDL_MT  MDL_WT    S 6
      -5 -2  -4   ZERO  ZERO    S 21
      -6 9  -5   ZERO  ZERO    S 21
      *     2       2
      -1 5  4   MDL_MW  MDL_WW    S 24
      -2 -1  3   MDL_MT  MDL_WT    S 6
      -3 9  -2   MDL_MT  MDL_WT    S 6
      -4 8  7   MDL_MW  MDL_WW    S -24
      -5 -4  6   MDL_MT  MDL_WT    S -6
      -6 -5  -3   ZERO  ZERO    S 21
      *     3       3
      -1 8  7   MDL_MW  MDL_WW    S -24
      -2 -1  6   MDL_MT  MDL_WT    S -6
      -3 9  -2   MDL_MT  MDL_WT    S -6
      -4 5  4   MDL_MW  MDL_WW    S 24
      -5 -4  3   MDL_MT  MDL_WT    S 6
      -6 -3  -5   ZERO  ZERO    S 21
      *     4       4
      -1 5  4   MDL_MW  MDL_WW    S 24
      -2 -1  3   MDL_MT  MDL_WT    S 6
      -3 8  7   MDL_MW  MDL_WW    S -24
      -4 -3  6   MDL_MT  MDL_WT    S -6
      -5 1  -2   MDL_MT  MDL_WT    T 6
      -6 -5  9   MDL_MT  MDL_WT    T 6
      *     5       5
      -1 5  4   MDL_MW  MDL_WW    S 24
      -2 -1  3   MDL_MT  MDL_WT    S 6
      -3 8  7   MDL_MW  MDL_WW    S -24
      -4 -3  6   MDL_MT  MDL_WT    S -6
      -5 1  -2   MDL_MT  MDL_WT    T 6
      -6 -5  -4   ZERO  ZERO    T 21
      *     6       6
      -1 8  7   MDL_MW  MDL_WW    S -24
      -2 -1  6   MDL_MT  MDL_WT    S -6
      -3 9  -2   MDL_MT  MDL_WT    S -6
      -4 5  4   MDL_MW  MDL_WW    S 24
      -5 -4  3   MDL_MT  MDL_WT    S 6
      -6 1  -5   MDL_MT  MDL_WT    T 6
      *     7       7
      -1 8  7   MDL_MW  MDL_WW    S -24
      -2 -1  6   MDL_MT  MDL_WT    S -6
      -3 5  4   MDL_MW  MDL_WW    S 24
      -4 -3  3   MDL_MT  MDL_WT    S 6
      -5 1  -2   MDL_MT  MDL_WT    T -6
      -6 -5  9   MDL_MT  MDL_WT    T -6
      *     8       8
      -1 8  7   MDL_MW  MDL_WW    S -24
      -2 -1  6   MDL_MT  MDL_WT    S -6
      -3 5  4   MDL_MW  MDL_WW    S 24
      -4 -3  3   MDL_MT  MDL_WT    S 6
      -5 1  -2   MDL_MT  MDL_WT    T -6
      -6 -5  -4   ZERO  ZERO    T 21
      *     9       9
      -1 8  7   MDL_MW  MDL_WW    S -24
      -2 -1  6   MDL_MT  MDL_WT    S -6
      -3 5  4   MDL_MW  MDL_WW    S 24
      -4 -3  3   MDL_MT  MDL_WT    S 6
      -5 9  -4   MDL_MT  MDL_WT    S 6
      -6 1  -2   MDL_MT  MDL_WT    T -6
      *     10       10
      -1 8  7   MDL_MW  MDL_WW    S -24
      -2 -1  6   MDL_MT  MDL_WT    S -6
      -3 5  4   MDL_MW  MDL_WW    S 24
      -4 -3  3   MDL_MT  MDL_WT    S 6
      -5 1  9   ZERO  ZERO    T 21
      -6 -5  -2   MDL_MT  MDL_WT    T -6
      *     11       11
      -1 5  4   MDL_MW  MDL_WW    S 24
      -2 -1  3   MDL_MT  MDL_WT    S 6
      -3 8  7   MDL_MW  MDL_WW    S -24
      -4 -3  6   MDL_MT  MDL_WT    S -6
      -5 1  9   ZERO  ZERO    T 21
      -6 -5  -2   MDL_MT  MDL_WT    T 6
      *     12       12
      -1 8  7   MDL_MW  MDL_WW    S -24
      -2 -1  6   MDL_MT  MDL_WT    S -6
      -3 5  4   MDL_MW  MDL_WW    S 24
      -4 -3  3   MDL_MT  MDL_WT    S 6
      -5 -2  -4   ZERO  ZERO    S 21
      -6 1  9   ZERO  ZERO    T 21
      *     13       13
      -1 8  7   MDL_MW  MDL_WW    S -24
      -2 -1  6   MDL_MT  MDL_WT    S -6
      -3 9  -2   MDL_MT  MDL_WT    S -6
      -4 5  4   MDL_MW  MDL_WW    S 24
      -5 -4  3   MDL_MT  MDL_WT    S 6
      -6 1  -3   MDL_MT  MDL_WT    T -6
      *     14       14
      -1 5  4   MDL_MW  MDL_WW    S 24
      -2 -1  3   MDL_MT  MDL_WT    S 6
      -3 9  -2   MDL_MT  MDL_WT    S 6
      -4 8  7   MDL_MW  MDL_WW    S -24
      -5 -4  6   MDL_MT  MDL_WT    S -6
      -6 1  -3   MDL_MT  MDL_WT    T 6
      *     15       15
      -1 8  7   MDL_MW  MDL_WW    S -24
      -2 -1  6   MDL_MT  MDL_WT    S -6
      -3 5  4   MDL_MW  MDL_WW    S 24
      -4 -3  3   MDL_MT  MDL_WT    S 6
      -5 -2  -4   ZERO  ZERO    S 21
      -6 1  -5   ZERO  ZERO    T 21
      *     16       16
      -1 8  7   MDL_MW  MDL_WW    S -24
      -2 -1  6   MDL_MT  MDL_WT    S -6
      -3 5  4   MDL_MW  MDL_WW    S 24
      -4 -3  3   MDL_MT  MDL_WT    S 6
      -5 -2  -4   ZERO  ZERO    S 21
      -6 9  -5   ZERO  ZERO    S 2
      *     17       17
      -1 5  4   MDL_MW  MDL_WW    S 24
      -2 -1  3   MDL_MT  MDL_WT    S 6
      -3 8  7   MDL_MW  MDL_WW    S -24
      -4 -3  6   MDL_MT  MDL_WT    S -6
      -5 1  -2   MDL_MT  MDL_WT    T 6
      -6 -5  -4   ZERO  ZERO    T 21
      *     18       18
      -1 8  7   MDL_MW  MDL_WW    S -24
      -2 -1  6   MDL_MT  MDL_WT    S -6
      -3 5  4   MDL_MW  MDL_WW    S 24
      -4 -3  3   MDL_MT  MDL_WT    S 6
      -5 1  -2   MDL_MT  MDL_WT    T -6
      -6 -5  -4   ZERO  ZERO    T 21
      *     19       19
      -1 8  7   MDL_MW  MDL_WW    S -24
      -2 -1  6   MDL_MT  MDL_WT    S -6
      -3 5  4   MDL_MW  MDL_WW    S 24
      -4 -3  3   MDL_MT  MDL_WT    S 6
      -5 -2  -4   ZERO  ZERO    S 21
      -6 1  9   ZERO  ZERO    T 2
      *     20       20
      -1 8  7   MDL_MW  MDL_WW    S -24
      -2 -1  6   MDL_MT  MDL_WT    S -6
      -3 5  4   MDL_MW  MDL_WW    S 24
      -4 -3  3   MDL_MT  MDL_WT    S 6
      -5 -2  -4   ZERO  ZERO    S 21
      -6 1  -5   ZERO  ZERO    T 21
      *     21       21
      -1 8  7   MDL_MW  MDL_WW    S -24
      -2 -1  6   MDL_MT  MDL_WT    S -6
      -3 5  4   MDL_MW  MDL_WW    S 24
      -4 -3  3   MDL_MT  MDL_WT    S 6
      -5 -2  -4   ZERO  ZERO    S 21
      -6 1  9   ZERO  ZERO    T -2
      *     22       22
      -1 5  4   MDL_MW  MDL_WW    S 24
      -2 -1  3   MDL_MT  MDL_WT    S 6
      -3 9  -2   MDL_MT  MDL_WT    S 6
      -4 8  7   MDL_MW  MDL_WW    S -24
      -5 -4  6   MDL_MT  MDL_WT    S -6
      -6 -5  -3   ZERO  ZERO    S 21
      *     23       23
      -1 8  7   MDL_MW  MDL_WW    S -24
      -2 -1  6   MDL_MT  MDL_WT    S -6
      -3 9  -2   MDL_MT  MDL_WT    S -6
      -4 5  4   MDL_MW  MDL_WW    S 24
      -5 -4  3   MDL_MT  MDL_WT    S 6
      -6 -3  -5   ZERO  ZERO    S 21
      *     24       24
      -1 8  7   MDL_MW  MDL_WW    S -24
      -2 -1  6   MDL_MT  MDL_WT    S -6
      -3 5  4   MDL_MW  MDL_WW    S 24
      -4 -3  3   MDL_MT  MDL_WT    S 6
      -5 -2  -4   ZERO  ZERO    S 21
      -6 1  -5   ZERO  ZERO    T -2
      *     25       25
      -1 8  7   MDL_MW  MDL_WW    S -24
      -2 -1  6   MDL_MT  MDL_WT    S -6
      -3 5  4   MDL_MW  MDL_WW    S 24
      -4 -3  3   MDL_MT  MDL_WT    S 6
      -5 -2  -4   ZERO  ZERO    S 21
      -6 9  -5   ZERO  ZERO    S 21
      *
