      *     1       1
      -1 8  7   MDL_MW  MDL_WW    S -24
      -2 -1  6   MDL_MT  MDL_WT    S -6
      -3 5  4   MDL_MW  MDL_WW    S 24
      -4 -3  3   MDL_MT  MDL_WT    S 6
      -5 -2  -4   ZERO  ZERO    S 21
      *     2       2
      -1 5  4   MDL_MW  MDL_WW    S 24
      -2 -1  3   MDL_MT  MDL_WT    S 6
      -3 8  7   MDL_MW  MDL_WW    S -24
      -4 -3  6   MDL_MT  MDL_WT    S -6
      -5 1  -2   MDL_MT  MDL_WT    T 6
      *     3       3
      -1 8  7   MDL_MW  MDL_WW    S -24
      -2 -1  6   MDL_MT  MDL_WT    S -6
      -3 5  4   MDL_MW  MDL_WW    S 24
      -4 -3  3   MDL_MT  MDL_WT    S 6
      -5 1  -2   MDL_MT  MDL_WT    T -6
      *     4       4
      -1 8  7   MDL_MW  MDL_WW    S -24
      -2 -1  6   MDL_MT  MDL_WT    S -6
      -3 5  4   MDL_MW  MDL_WW    S 24
      -4 -3  3   MDL_MT  MDL_WT    S 6
      -5 -2  -4   ZERO  ZERO    S 21
      *
