      DOUBLE PRECISION FUNCTION DSIG(PP,WGT)
C     ****************************************************
C     
C     Generated by MadGraph5_aMC@NLO v. 2.1.0.beta, 2014-02-18
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Process: g g > t t~ NP=2 QED=2 @1 NP=2 QED=2 
C     *   Decay: t > b w+ NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w+ > mu+ vm NP=2 QED=2 @0 NP=2 QED=2 
C     *   Decay: t~ > b~ w- NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w- > d u~ NP=2 QED=2 @0 NP=2 QED=2 
C     Process: g g > t t~ NP=2 QED=2 @1 NP=2 QED=2 
C     *   Decay: t > b w+ NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w+ > mu+ vm NP=2 QED=2 @0 NP=2 QED=2 
C     *   Decay: t~ > b~ w- NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w- > d c~ NP=2 QED=2 @0 NP=2 QED=2 
C     Process: g g > t t~ NP=2 QED=2 @1 NP=2 QED=2 
C     *   Decay: t > b w+ NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w+ > mu+ vm NP=2 QED=2 @0 NP=2 QED=2 
C     *   Decay: t~ > b~ w- NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w- > s u~ NP=2 QED=2 @0 NP=2 QED=2 
C     Process: g g > t t~ NP=2 QED=2 @1 NP=2 QED=2 
C     *   Decay: t > b w+ NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w+ > mu+ vm NP=2 QED=2 @0 NP=2 QED=2 
C     *   Decay: t~ > b~ w- NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w- > s c~ NP=2 QED=2 @0 NP=2 QED=2 
C     Process: u u~ > t t~ NP=2 QED=2 @1 NP=2 QED=2 
C     *   Decay: t > b w+ NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w+ > mu+ vm NP=2 QED=2 @0 NP=2 QED=2 
C     *   Decay: t~ > b~ w- NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w- > d u~ NP=2 QED=2 @0 NP=2 QED=2 
C     Process: c c~ > t t~ NP=2 QED=2 @1 NP=2 QED=2 
C     *   Decay: t > b w+ NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w+ > mu+ vm NP=2 QED=2 @0 NP=2 QED=2 
C     *   Decay: t~ > b~ w- NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w- > d u~ NP=2 QED=2 @0 NP=2 QED=2 
C     Process: d d~ > t t~ NP=2 QED=2 @1 NP=2 QED=2 
C     *   Decay: t > b w+ NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w+ > mu+ vm NP=2 QED=2 @0 NP=2 QED=2 
C     *   Decay: t~ > b~ w- NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w- > d u~ NP=2 QED=2 @0 NP=2 QED=2 
C     Process: s s~ > t t~ NP=2 QED=2 @1 NP=2 QED=2 
C     *   Decay: t > b w+ NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w+ > mu+ vm NP=2 QED=2 @0 NP=2 QED=2 
C     *   Decay: t~ > b~ w- NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w- > d u~ NP=2 QED=2 @0 NP=2 QED=2 
C     Process: u u~ > t t~ NP=2 QED=2 @1 NP=2 QED=2 
C     *   Decay: t > b w+ NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w+ > mu+ vm NP=2 QED=2 @0 NP=2 QED=2 
C     *   Decay: t~ > b~ w- NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w- > d c~ NP=2 QED=2 @0 NP=2 QED=2 
C     Process: c c~ > t t~ NP=2 QED=2 @1 NP=2 QED=2 
C     *   Decay: t > b w+ NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w+ > mu+ vm NP=2 QED=2 @0 NP=2 QED=2 
C     *   Decay: t~ > b~ w- NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w- > d c~ NP=2 QED=2 @0 NP=2 QED=2 
C     Process: d d~ > t t~ NP=2 QED=2 @1 NP=2 QED=2 
C     *   Decay: t > b w+ NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w+ > mu+ vm NP=2 QED=2 @0 NP=2 QED=2 
C     *   Decay: t~ > b~ w- NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w- > d c~ NP=2 QED=2 @0 NP=2 QED=2 
C     Process: s s~ > t t~ NP=2 QED=2 @1 NP=2 QED=2 
C     *   Decay: t > b w+ NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w+ > mu+ vm NP=2 QED=2 @0 NP=2 QED=2 
C     *   Decay: t~ > b~ w- NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w- > d c~ NP=2 QED=2 @0 NP=2 QED=2 
C     Process: u u~ > t t~ NP=2 QED=2 @1 NP=2 QED=2 
C     *   Decay: t > b w+ NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w+ > mu+ vm NP=2 QED=2 @0 NP=2 QED=2 
C     *   Decay: t~ > b~ w- NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w- > s u~ NP=2 QED=2 @0 NP=2 QED=2 
C     Process: c c~ > t t~ NP=2 QED=2 @1 NP=2 QED=2 
C     *   Decay: t > b w+ NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w+ > mu+ vm NP=2 QED=2 @0 NP=2 QED=2 
C     *   Decay: t~ > b~ w- NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w- > s u~ NP=2 QED=2 @0 NP=2 QED=2 
C     Process: d d~ > t t~ NP=2 QED=2 @1 NP=2 QED=2 
C     *   Decay: t > b w+ NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w+ > mu+ vm NP=2 QED=2 @0 NP=2 QED=2 
C     *   Decay: t~ > b~ w- NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w- > s u~ NP=2 QED=2 @0 NP=2 QED=2 
C     Process: s s~ > t t~ NP=2 QED=2 @1 NP=2 QED=2 
C     *   Decay: t > b w+ NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w+ > mu+ vm NP=2 QED=2 @0 NP=2 QED=2 
C     *   Decay: t~ > b~ w- NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w- > s u~ NP=2 QED=2 @0 NP=2 QED=2 
C     Process: u u~ > t t~ NP=2 QED=2 @1 NP=2 QED=2 
C     *   Decay: t > b w+ NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w+ > mu+ vm NP=2 QED=2 @0 NP=2 QED=2 
C     *   Decay: t~ > b~ w- NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w- > s c~ NP=2 QED=2 @0 NP=2 QED=2 
C     Process: c c~ > t t~ NP=2 QED=2 @1 NP=2 QED=2 
C     *   Decay: t > b w+ NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w+ > mu+ vm NP=2 QED=2 @0 NP=2 QED=2 
C     *   Decay: t~ > b~ w- NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w- > s c~ NP=2 QED=2 @0 NP=2 QED=2 
C     Process: d d~ > t t~ NP=2 QED=2 @1 NP=2 QED=2 
C     *   Decay: t > b w+ NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w+ > mu+ vm NP=2 QED=2 @0 NP=2 QED=2 
C     *   Decay: t~ > b~ w- NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w- > s c~ NP=2 QED=2 @0 NP=2 QED=2 
C     Process: s s~ > t t~ NP=2 QED=2 @1 NP=2 QED=2 
C     *   Decay: t > b w+ NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w+ > mu+ vm NP=2 QED=2 @0 NP=2 QED=2 
C     *   Decay: t~ > b~ w- NP=2 QED=2 @0 NP=2 QED=2 
C     *     Decay: w- > s c~ NP=2 QED=2 @0 NP=2 QED=2 
C     
C     RETURNS DIFFERENTIAL CROSS SECTION 
C     FOR MULTIPLE PROCESSES IN PROCESS GROUP
C     Input:
C     pp    4 momentum of external particles
C     wgt   weight from Monte Carlo
C     Output:
C     Amplitude squared and summed
C     ****************************************************
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INCLUDE 'nexternal.inc'
      INCLUDE 'maxamps.inc'
      REAL*8     PI
      PARAMETER (PI=3.1415926D0)
C     
C     ARGUMENTS 
C     
      DOUBLE PRECISION PP(0:3,NEXTERNAL), WGT
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J,K,ICONF,IMIRROR,NPROC
      SAVE NPROC
      LOGICAL MIRRORPROCS(MAXSPROC)
      INCLUDE 'mirrorprocs.inc'
      DOUBLE PRECISION XDUM
C     
C     EXTERNAL FUNCTIONS
C     
      DOUBLE PRECISION DSIGPROC
      EXTERNAL DSIGPROC
C     
C     GLOBAL VARIABLES
C     
      INCLUDE 'coupl.inc'
      INCLUDE 'run.inc'
C     IPROC has the present process number
      INTEGER IPROC
      COMMON/TO_MIRROR/IMIRROR, IPROC
C     ----------
C     BEGIN CODE
C     ----------
      DSIG=0D0


C     Select among the subprocesses based on PDF weight
      DO IPROC=1,MAXSPROC
        DO IMIRROR=1,2
          IF(IMIRROR.EQ.1.OR.MIRRORPROCS(IPROC))THEN
            DSIG=DSIG+DSIGPROC(PP,IPROC,IMIRROR)
            IF(IMIRROR.EQ.2)THEN
C             Need to flip back x values
              XDUM=XBK(1)
              XBK(1)=XBK(2)
              XBK(2)=XDUM
            ENDIF
          ENDIF
        ENDDO
      ENDDO


      RETURN
      END

      FUNCTION DSIGPROC(PP,IPROC,IMIRROR)
C     ****************************************************
C     RETURNS DIFFERENTIAL CROSS SECTION 
C     FOR A PROCESS
C     Input:
C     pp    4 momentum of external particles
C     wgt   weight from Monte Carlo
C     Output:
C     Amplitude squared and summed
C     ****************************************************

      IMPLICIT NONE

      INCLUDE 'nexternal.inc'
      INCLUDE 'maxamps.inc'
      INCLUDE 'coupl.inc'
      INCLUDE 'run.inc'
C     
C     ARGUMENTS 
C     
      DOUBLE PRECISION DSIGPROC
      DOUBLE PRECISION PP(0:3,NEXTERNAL), WGT
      INTEGER IPROC,IMIRROR
C     
C     GLOBAL VARIABLES
C     
C     SUBDIAG is vector of diagram numbers for this config
C     IB gives which beam is which (for mirror processes)
      INTEGER SUBDIAG(MAXSPROC),IB(2)
      COMMON/TO_SUB_DIAG/SUBDIAG,IB
C     
C     EXTERNAL FUNCTIONS
C     
      DOUBLE PRECISION DSIG1,DSIG2,DSIG3,DSIG4,DSIG5,DSIG6,DSIG7,DSIG8
      LOGICAL PASSCUTS
C     
C     LOCAL VARIABLES 
C     
      DOUBLE PRECISION P1(0:3,NEXTERNAL),XDUM
      DOUBLE PRECISION PTEMP(0:3)
      INTEGER I,J,K
      INTEGER IMODE

      IMODE=1  ! DUMMY VARIABLE
      DO I=1,NEXTERNAL
        DO J=0,3
          P1(J,I)=PP(J,I)
        ENDDO
      ENDDO

      IB(1)=1
      IB(2)=2

      IF(IMIRROR.EQ.2)THEN
        DO I=0,3
          PTEMP(I)=P1(I,1)
          P1(I,1)=P1(I,2)
          P1(I,2)=PTEMP(I)
        ENDDO
C       Flip x values 
        XDUM=XBK(1)
        XBK(1)=XBK(2)
        XBK(2)=XDUM
      ENDIF

      DSIGPROC=0D0

      IF(IPROC.EQ.1) DSIGPROC=DSIG1(P1,WGT,IMODE)  ! g g > b mu+ vm b~ d u~
      IF(IPROC.EQ.2) DSIGPROC=DSIG2(P1,WGT,IMODE)  ! g g > b mu+ vm b~ d c~
      IF(IPROC.EQ.3) DSIGPROC=DSIG3(P1,WGT,IMODE)  ! g g > b mu+ vm b~ s u~
      IF(IPROC.EQ.4) DSIGPROC=DSIG4(P1,WGT,IMODE)  ! g g > b mu+ vm b~ s c~
      IF(IPROC.EQ.5) DSIGPROC=DSIG5(P1,WGT,IMODE)  ! u u~ > b mu+ vm b~ d u~
      IF(IPROC.EQ.6) DSIGPROC=DSIG6(P1,WGT,IMODE)  ! u u~ > b mu+ vm b~ d c~
      IF(IPROC.EQ.7) DSIGPROC=DSIG7(P1,WGT,IMODE)  ! u u~ > b mu+ vm b~ s u~
      IF(IPROC.EQ.8) DSIGPROC=DSIG8(P1,WGT,IMODE)  ! u u~ > b mu+ vm b~ s c~
      RETURN
      END


