ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of MassiveLeptons-MassiveLeptons'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_6 = ', GC_6
      WRITE(*,2) 'GC_7 = ', GC_7
      WRITE(*,2) 'GC_17 = ', GC_17
      WRITE(*,2) 'GC_22 = ', GC_22
      WRITE(*,2) 'GC_23 = ', GC_23
      WRITE(*,2) 'GC_31 = ', GC_31
      WRITE(*,2) 'GC_32 = ', GC_32
      WRITE(*,2) 'GC_42 = ', GC_42
      WRITE(*,2) 'GC_43 = ', GC_43
      WRITE(*,2) 'GC_44 = ', GC_44
      WRITE(*,2) 'GC_45 = ', GC_45
