ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' External Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'RVL = ', RVL
      WRITE(*,*) 'IVL = ', IVL
      WRITE(*,*) 'RVR = ', RVR
      WRITE(*,*) 'IVR = ', IVR
      WRITE(*,*) 'RgL = ', RGL
      WRITE(*,*) 'IgL = ', IGL
      WRITE(*,*) 'RgR = ', RGR
      WRITE(*,*) 'IgR = ', IGR
      WRITE(*,*) 'cabi = ', CABI
      WRITE(*,*) 'aEWM1 = ', AEWM1
      WRITE(*,*) 'Gf = ', GF
      WRITE(*,*) 'aS = ', AS
      WRITE(*,*) 'ymb = ', YMB
      WRITE(*,*) 'ymt = ', YMT
      WRITE(*,*) 'yme = ', YME
      WRITE(*,*) 'ymm = ', YMM
      WRITE(*,*) 'ymtau = ', YMTAU
      WRITE(*,*) 'MZ = ', MZ
      WRITE(*,*) 'Me = ', ME
      WRITE(*,*) 'MM = ', MM
      WRITE(*,*) 'MTA = ', MTA
      WRITE(*,*) 'MT = ', MT
      WRITE(*,*) 'MB = ', MB
      WRITE(*,*) 'MH = ', MH
      WRITE(*,*) 'WZ = ', WZ
      WRITE(*,*) 'WW = ', WW
      WRITE(*,*) 'WT = ', WT
      WRITE(*,*) 'WH = ', WH
      WRITE(*,*)  ' Internal Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'cos__cabi = ', COS__CABI
      WRITE(*,*) 'CKM11 = ', CKM11
      WRITE(*,*) 'sin__cabi = ', SIN__CABI
      WRITE(*,*) 'CKM12 = ', CKM12
      WRITE(*,*) 'CKM21 = ', CKM21
      WRITE(*,*) 'CKM22 = ', CKM22
      WRITE(*,*) 'CouplingW = ', COUPLINGW
      WRITE(*,*) 'EWCoupl = ', EWCOUPL
      WRITE(*,*) 'g1 = ', G1
      WRITE(*,*) 'complexi = ', COMPLEXI
      WRITE(*,*) 'gL = ', GL
      WRITE(*,*) 'gR = ', GR
      WRITE(*,*) 'gw = ', GW
      WRITE(*,*) 'VL = ', VL
      WRITE(*,*) 'VR = ', VR
      WRITE(*,*) 'MZ__exp__2 = ', MZ__EXP__2
      WRITE(*,*) 'MZ__exp__4 = ', MZ__EXP__4
      WRITE(*,*) 'sqrt__2 = ', SQRT__2
      WRITE(*,*) 'sqrt__EWCoupl = ', SQRT__EWCOUPL
      WRITE(*,*) 'ElecC = ', ELECC
      WRITE(*,*) 'MH__exp__2 = ', MH__EXP__2
      WRITE(*,*) 'conjg__CKM11 = ', CONJG__CKM11
      WRITE(*,*) 'conjg__CKM12 = ', CONJG__CKM12
      WRITE(*,*) 'conjg__CKM21 = ', CONJG__CKM21
      WRITE(*,*) 'conjg__CKM22 = ', CONJG__CKM22
      WRITE(*,*) 'conjg__gL = ', CONJG__GL
      WRITE(*,*) 'conjg__gR = ', CONJG__GR
      WRITE(*,*) 'conjg__VL = ', CONJG__VL
      WRITE(*,*) 'conjg__VR = ', CONJG__VR
      WRITE(*,*) 'aEW = ', AEW
      WRITE(*,*) 'MW = ', MW
      WRITE(*,*) 'sqrt__aEW = ', SQRT__AEW
      WRITE(*,*) 'ee = ', EE
      WRITE(*,*) 'MW__exp__2 = ', MW__EXP__2
      WRITE(*,*) 'sw2 = ', SW2
      WRITE(*,*) 'cw = ', CW
      WRITE(*,*) 'sqrt__sw2 = ', SQRT__SW2
      WRITE(*,*) 'sw = ', SW
      WRITE(*,*) 'vev = ', VEV
      WRITE(*,*) 'vev__exp__2 = ', VEV__EXP__2
      WRITE(*,*) 'lam = ', LAM
      WRITE(*,*) 'yb = ', YB
      WRITE(*,*) 'ye = ', YE
      WRITE(*,*) 'ym = ', YM
      WRITE(*,*) 'yt = ', YT
      WRITE(*,*) 'ytau = ', YTAU
      WRITE(*,*) 'muH = ', MUH
      WRITE(*,*) 'ee__exp__2 = ', EE__EXP__2
      WRITE(*,*) 'sw__exp__2 = ', SW__EXP__2
      WRITE(*,*) 'cw__exp__2 = ', CW__EXP__2
      WRITE(*,*)  ' Internal Params evaluated point by point'
      WRITE(*,*)  ' ----------------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'sqrt__aS = ', SQRT__AS
      WRITE(*,*) 'G__exp__2 = ', G__EXP__2
