C automatic include file for card /grid_mnt/storage__localgrid/aolbrech/NewestMW_amcnlo_PTDependentTF/mg5amcnlo/ttbarSemiMuPlus_QED2_CKMRestrictions/Cards/MadWeight_card.dat and ./Cards/ident_mw_card.dat

        use_cut = .false.
        nevents_refine = 10000
        use_sobol = .false.
        histo = .false.
        bw_cut = .false.
        isr = 0
        final_prec = 5.000000d-03
        value_cut1 = 0.000000d+00
        min_prec_cut1 = 5.000000d-04
        max_it_step1 = 2
        max_it_step3 = 0
        max_it_step2 = 16
        max_it_step5 = 0
        max_it_step4 = 0
        min_prec_cut2 = 0.000000d+00
        value_cut2 = 0.000000d+00
        integrator = 0
        nevents = 2000
        pretrained = .true.
        nwa = 0.1
        perm_with_b = .false.
        montecarlo_perm = .true.
        min_perm_cut = 5.000000d-04
        use_perm = .true.
